schema_version = "1.0.0"

id = "nalana"
version = "0.5.0"
name = "Nalana"
tagline = "Voice-Controlled 3D Creation for Blender"
description = "Nalana allows you to build 3D scenes in Blender using real-time voice commands and AI."
maintainers = ["Nalana Team"]
type = "add-on"
blender_version_min = "4.2.0"

# A list of tags for the extension.
tags = ["System"]

# Optional: Link to the issue tracker or source code.
url = "https://github.com/cekeith999/Nalana-datasc"
